//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int Id { get; set; }
        public Nullable<int> GoodsId { get; set; }
        public Nullable<int> PurchaserId { get; set; }
        public string BuyPrice { get; set; }
        public Nullable<System.DateTime> BuyTime { get; set; }
        public string SendAddress { get; set; }
        public string PayType { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Tel { get; set; }
        public string Evaluate { get; set; }
        public Nullable<System.DateTime> EvaluateTime { get; set; }
        public string EvaluateState { get; set; }
        public string WuliState { get; set; }
    
        public virtual GoodsInfo GoodsInfo { get; set; }
        public virtual Purchaser Purchaser { get; set; }
    }
}
